#docker-compose -f camunda-drawtul.yml up -d
version: '3.8'

services:
  mongodb:
    image: mongo:5.0.6-focal
    container_name: mongodb

  mysqldb:
    image: mysql:8.0.27
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camunda
    volumes:
      - mysql-dir:/data/db

  camunda:
    image: uzrnem/camunda:0.0.1-beta
    container_name: camunda
    environment:
      CORS_ALLOWED_APP_URL: http://localhost:8082
      CAMUNDA_WEB_APP_PORT: 8080
      CAMUNDA_JDBC_URL: jdbc:mysql://mysqldb:3306/camunda
      CAMUNDA_JDBC_USER: root
      CAMUNDA_JDBC_PASSWORD: root
      CAMUNDA_ADMIN_USER: admin
      CAMUNDA_ADMIN_PASSWORD: changeme
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

  drawtul:
    image: uzrnem/drawtul:0.0.1-beta
    container_name: drawtul
    environment:
      CAMUNDA_WEB_APP_URL: http://localhost:8080
      EXTENTION_BACKEND_APP_PORT: 8082
    ports:
      - 8082:8082
    depends_on:
      - mongodb

volumes:
  mysql-dir: