#docker-compose -f mongodb-expressui.yml up -d
version: "3.7"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    # environment:
    #  - MONGO_INITDB_ROOT_USERNAME=root
    #  - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      #local dir/files: docker dir/files
      - $HOME/uzrnem/db/mongo_db:/data/db
      - $HOME/uzrnem/db/credentials:/credentials
    ports:
      - 27017:27017
    networks:
      - mongo-database
    #echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      #- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=root
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    volumes:
      - $HOME/uzrnem/db/mongo_db
    ports:
      - 8002:8081
    networks:
      - mongo-database
    # wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1

networks:
  mongo-database: # docker-compose-files_mongo-database
    driver: bridge