#docker-compose -f mysql-phpmyadmin.yml up -d
#docker container run -p 3306:3306 --name=mysql -e MYSQL_ROOT_PASSWORD="root" mysql:8.0.27
version: "3.7"

services:
  mysqldb:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test_db
    ports:
      - 3306:3306
    volumes:
      #local dir/files: docker dir/files
      - $HOME/uzrnem/database/mysql_db:/var/lib/mysql
      - $HOME/uzrnem/database/backup:/backup
    networks:
      - mysql-database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: mysqladmin
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1 // IF HOST is required, in case of local mysql and docker php myadmin
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8000:80
    networks:
      - mysql-database

networks:
  mysql-database: # docker-compose-files_mysql-database
    driver: bridge