#docker-compose -f nginx-lua.yml up -d
version: '3.7'

services:
  nginx:
    image: fabiocicerchia/nginx-lua:latest
    container: nginx
    restart: always
    volumes:
      - ./templates:/etc/nginx/templates
  #    - /path/to/docroot:/var/www/html
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80" #8080
      - "443:443"
  #  environment:
  #    - NGINX_HOST=foobar.com
  #    - NGINX_PORT=80
  #  healthcheck:
  #    test: ['CMD', 'curl --fail http://localhost/ || exit 1']
  #    interval: 30s
  #    timeout: 3s
  #    retries: 3


#    image: nginx:stable-alpine //1.21.3-alpine3.14.2,latest
#    ports: "8088:80"
#    volumes:
#      - ./src:/var/www/html
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf