#docker-compose up --build
version: '3.7'

services:
  java:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: java
    expose:
      - "9040"
    volumes:
      - $HOME/projects/docker-compose-files/java-docker-image-example/javaenv:/programs
    ports:
      - "9040:9040"
