#docker-compose -f java.yml up -d
version: '3.7'

services:
  java_environment:
    image: openjdk:16-alpine3.13 #mac openjdk:19-slim
    container_name: javaenv
    working_dir: /programs
    volumes:
      - $HOME/uzrnem/programs/java:/programs
    command: tail -f /dev/null
    #env_file: ../sample/.env-local