#docker-compose -f mysql-phpmyadmin.yml up -d
#docker container run -p 3306:3306 --name=mysql -e MYSQL_ROOT_PASSWORD="root" mysql:8.0.27
version: "3.7"

services:
  mysqldb:
    image: mysql:8.0.28 # mac: mysql:8.0.28-oracle
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test_db
    ports:
      - 3306:3306
    volumes:
      #local dir/files: docker dir/files
      - $HOME/uzrnem/database/mysql_db:/var/lib/mysql
      - $HOME/uzrnem/database/backup:/backup
    networks:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: mysqladmin
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1 // IF HOST is required, in case of local mysql and docker php myadmin
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8000:80
    networks:
      - mysql

networks:
  mysql: # database_mysql
    driver: bridge

#If you face issue connecting
# CREATE USER 'USERNAME' IDENTIFIED BY 'password';
# GRANT ALL PRIVILEGES ON *.* TO 'USERNAME' WITH GRANT OPTION;
# ALTER USER 'USERNAME' IDENTIFIED WITH mysql_native_password BY 'PASSWORD';
# FLUSH PRIVILEGES;
# ***replace USERNAME and PASSWORD only and not password
