#docker-compose -f redis.yml up -d
version: "3.7"

services:
  redis:
    image: redis:6.2.6-alpine3.15
    container_name: redis
    command: redis-server --requirepass redis
    volumes:
      - $HOME/uzrnem/database/redis:/data
    ports:
      - 6379:6379
    networks:
      - redis

networks:
  redis: # database_redis
    driver: bridge
